version = 0.1

[default.global.parameters]
stack_name = "ecoshift"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "ecoshift"
region = "us-west-2"
image_repositories = []
parameter_overrides = [
  "GridZone=US-NW-PACW",
  "GreenThresholdGCO2=250",
  "MaxVcpusGreen=16",
  "MaxVcpusDirty=0",
  "BedrockModelId=us.amazon.nova-lite-v1:0",
  "ReportEmail=adamle11488@gmail.com",
  "MockCarbon=0",
  "VpcId=vpc-0742a38754f338a6d",
  "SubnetIds=subnet-0990d6c4af3083de0,subnet-039d9aa5bca7e8338,subnet-07ccef1b0abe33872,subnet-07c837c4a60af74e7"
]
