import React from 'react'
import ReactMarkdown from 'react-markdown'

export default function DailySummary({ summary }) {
  if (!summary) {
    return <div className="loader">No daily summary generated yet. First report runs at 23:55 UTC (or invoke the reporter Lambda manually).</div>
  }
  return (
    <div>
      <div className="subtle" style={{ marginBottom: 8 }}>Generated by Amazon Bedrock · {summary.date}</div>
      <div className="narrative">
        <ReactMarkdown>{summary.narrative || ''}</ReactMarkdown>
      </div>
    </div>
  )
}
