import React, { useEffect, useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'

function formatDate(s) {
  if (!s) return ''
  try {
    return new Date(s).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
  } catch { return s }
}

function nextUtcMidnight(from = new Date()) {
  return new Date(Date.UTC(
    from.getUTCFullYear(),
    from.getUTCMonth(),
    from.getUTCDate() + 1,
    0, 0, 0, 0
  ))
}

function formatCountdown(ms) {
  const total = Math.max(0, Math.ceil(ms / 1000))
  const hours = Math.floor(total / 3600)
  const minutes = Math.floor((total % 3600) / 60)
  const seconds = total % 60
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`
}

export default function DailySummary({ summary }) {
  const [now, setNow] = useState(() => new Date())

  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), 1000)
    return () => clearInterval(id)
  }, [])

  const nextReportAt = useMemo(() => nextUtcMidnight(now), [now])
  const countdown = formatCountdown(nextReportAt.getTime() - now.getTime())
  const nextTime = nextReportAt.toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
    timeZone: 'UTC',
    timeZoneName: 'short',
  })

  return (
    <div>
      <div className="report-timer">
        <span>Next daily report</span>
        <strong>{countdown}</strong>
        <span>{nextTime}</span>
      </div>

      {!summary ? (
        <div className="loader">No daily brief yet. Reporter runs daily at 00:00 UTC.</div>
      ) : (
        <>
          <div className="narrative-byline">
            Generated by Amazon Bedrock (Claude Sonnet 4.6) - {formatDate(summary.date)}
          </div>
          <div className="narrative">
            <ReactMarkdown>{summary.narrative || ''}</ReactMarkdown>
          </div>
        </>
      )}
    </div>
  )
}
