import React from 'react'
import ReactMarkdown from 'react-markdown'

function formatDate(s) {
  if (!s) return ''
  try {
    return new Date(s).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
  } catch { return s }
}

export default function DailySummary({ summary }) {
  if (!summary) {
    return <div className="loader">No daily brief yet — first report runs at 23:55 UTC.</div>
  }
  return (
    <div>
      <div className="narrative-byline">
        Generated by Amazon Bedrock (Claude Sonnet 4.6) · {formatDate(summary.date)}
      </div>
      <div className="narrative">
        <ReactMarkdown>{summary.narrative || ''}</ReactMarkdown>
      </div>
    </div>
  )
}
